# Generated by Django 5.0.1 on 2024-02-01 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Participent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique="True")),
            ],
        ),
        migrations.CreateModel(
            name="Meetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "organizer_email",
                    models.EmailField(default="email@gmail.com", max_length=254),
                ),
                ("date", models.DateField(default="2021-04-12")),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images")),
                (
                    "location",
                    models.ForeignKey(
                        default="New York",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meetuos.location",
                    ),
                ),
                (
                    "participent",
                    models.ManyToManyField(
                        blank=True, null=True, to="meetuos.participent"
                    ),
                ),
            ],
        ),
    ]
