# Generated by Django 5.0.1 on 2024-02-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetuos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="meetup",
            name="participent",
            field=models.ManyToManyField(blank=True, to="meetuos.participent"),
        ),
    ]
