# Generated by Django 5.0.1 on 2024-02-04 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetuos", "0002_alter_meetup_organizer_email_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Participent",
            new_name="Participant",
        ),
    ]
